### ISSUE TITLE
Why pivot table with plurals?

### ISSUE THREAD

**Issue by mikylucky** [jarektkaczyk/Eloquent-triple-pivot#12]
Laravel default pivot tables are using singular names of the models, should not be the same in this project?

**Comment by jarektkaczyk** [comment]
I can't see plurals here https://github.com/jarektkaczyk/Eloquent-triple-pivot/blob/master/src/Jarektkaczyk/TriplePivot/TriplePivotTrait.php#L100-L111 ?

**Comment by mikylucky** [comment]
In the example in the readme plurals are used in the setup section

https://github.com/jarektkaczyk/Eloquent-triple-pivot#setup

**Comment by jarektkaczyk** [comment]
Right, fixed it. Anyway it's not maintained anymore and it works with L4 only.

**Comment by mikylucky** [comment]
I saw there is a pull request to update it to L5.1! I haven't seen the code yet but I think it's worth checking
