### ISSUE TITLE
Return all tracks as a Collection

### ISSUE THREAD

**Issue by lasselehtinen** [jarektkaczyk/Eloquent-triple-pivot#6]
Hi,

My question is little bit similar as in https://github.com/jarektkaczyk/Eloquent-triple-pivot/issues/5. In my use case there might be more than one track associated. I can attach them just fine, but I would like to get the Collection back as in $users->tags. How can I achieve this?

**Comment by jarektkaczyk** [comment]
It's exactly the same problem and you cannot do it currently. I need to fix it (or PR would be awesome). Unfortunately I couldn't make it so far, so please stay tuned - matter of a few days.
