### ISSUE TITLE
sync() method

### ISSUE THREAD

**Issue by adanarchila** [jarektkaczyk/Eloquent-triple-pivot#7]
Hi, thanks a for this great package, it made my life lot easier these past few days. 

I've search on the documentation but I didn't find anything related to the sync() method I only found attach() which is working pretty good, but if I need to edit update which IDs are attached to my model I can't do it. Are you planning to integrate the sync() method or do you have other alternatives? 

Thanks!

**Comment by jarektkaczyk** [comment]
Yes, It was on purpose. When using `sync` you can easily mimic the behaviour:

```
$model->relation()->sync([

   'id_1' => ['third_id' => 5],
   'id_2' => ['third_id' => 6],
   'id_3' => ['third_id' => 7],

]);
```

Let me know if something is unclear.

**Comment by adanarchila** [comment]
Thanks a lot, it worked perfectly.
